# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='studentnum',
            field=models.CharField(max_length=32),
        ),
    ]
