# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20160918_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password1', models.CharField(max_length=32)),
                ('password2', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('idnumber', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('home', models.CharField(max_length=32)),
            ],
        ),
    ]
