# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=32),
        ),
    ]
